name: Development Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: devolopment
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
